# Generated by Django 4.1.7 on 2023-04-16 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('teaching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingstasks',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='id пользователь'),
        ),
        migrations.AddField(
            model_name='taskscontrol',
            name='id_control_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teaching.controlworks', verbose_name='id контрольной работы'),
        ),
        migrations.AddField(
            model_name='taskscontrol',
            name='id_stud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.students', verbose_name='id студента'),
        ),
        migrations.AddField(
            model_name='taskscontrol',
            name='id_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teaching.tasks', verbose_name='id задачи'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='id_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.teachers', verbose_name='id преподователя'),
        ),
        migrations.AddField(
            model_name='controlworkstatus',
            name='id_control_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teaching.controlworks', verbose_name='id контрольной работы'),
        ),
        migrations.AddField(
            model_name='controlworkstatus',
            name='id_stud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.students', verbose_name='id студента'),
        ),
        migrations.AddField(
            model_name='controlworks',
            name='id_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.teachers', verbose_name='id преподователя'),
        ),
    ]
