# Generated by Django 4.1.2 on 2022-12-17 06:45

from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('login_data_str', django_jsonform.models.fields.ArrayField(base_field=django_jsonform.models.fields.ArrayField(base_field=models.TextField(), size=None), blank=True, null=True, size=10)),
                ('answer_str', django_jsonform.models.fields.ArrayField(base_field=django_jsonform.models.fields.ArrayField(base_field=models.TextField(), size=None), blank=True, null=True, size=10)),
            ],
            options={
                'verbose_name': 'Задачи',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='TaskUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('solution', models.BooleanField(blank=True, null=True)),
                ('id_tasks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teaching.tasks')),
            ],
            options={
                'verbose_name': 'Задача/Пользователь',
                'verbose_name_plural': 'Задача/Пользователь',
            },
        ),
    ]
